version: '2.3'
services:
  q-server:
    build:
      context: ./build
    # image: tonlabs/q-server:latest
    container_name: q-server
    restart: unless-stopped
    environment:
      Q_DATA_MUT: '{{ Q_DATA_MUT }}'
      Q_DATA_HOT: '{{ Q_DATA_HOT }}'
      Q_SLOW_QUERIES_MUT: '{{ Q_SLOW_QUERIES_MUT }}'
      Q_SLOW_QUERIES_HOT: '{{ Q_SLOW_QUERIES_HOT }}'
      Q_REQUESTS_MODE: '{{ Q_REQUESTS_MODE }}'
      Q_REQUESTS_SERVER: '{{ Q_REQUESTS_SERVER }}'
      Q_REQUESTS_TOPIC: '{{ Q_REQUESTS_TOPIC }}'
      Q_DATABASE_MAX_SOCKETS: '{{ Q_DATABASE_MAX_SOCKETS }}'
      Q_SLOW_DATABASE_MAX_SOCKETS: '{{ Q_SLOW_DATABASE_MAX_SOCKETS }}'
      Q_STATSD_SERVER: '{{ inventory_hostname }}:9125'
    networks:
      - proxy_nw
    expose:
      - "4000"
    mem_limit: 5G

networks:
  proxy_nw:
    external: true
