version: '2.3'
services:
  q-server:
    build:
      context: ./build
    container_name: q-server
    restart: unless-stopped
    environment:
      Q_HOST: "localhost"
      Q_DATA_MUT: 'http://localhost:8529'
      Q_DATA_HOT: 'http://localhost:8529'
      Q_SLOW_QUERIES_MUT: 'http://localhost:8530'
      Q_SLOW_QUERIES_HOT: 'http://localhost:8530'
      Q_REQUESTS_MODE: 'kafka'
      Q_REQUESTS_SERVER: 'localhost:9092'
      Q_REQUESTS_TOPIC: 'requests'
      Q_DATABASE_MAX_SOCKETS: '100'
      Q_SLOW_DATABASE_MAX_SOCKETS: '20'
      Q_STATSD_SERVER: 'localhost:9125'
    network_mode: host
    mem_limit: 5G
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    network_mode: host
