version: '2.3'
services:
  proxy:
    build:
      context: ./build
    #        image: jwilder/nginx-proxy:latest
    container_name: proxy
    restart: unless-stopped
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    security_opt:
      - label:type:docker_t
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_nw
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl/docker:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf
{% if auth == true %}
      - ./htpasswd:/etc/nginx/htpasswd
{% endif %}
    healthcheck:
      test: grep -q -e 00000000:0050 -e 00000000:01BB /proc/net/tcp
      interval: 1m30s
      timeout: 3s
      retries: 3
      start_period: 40s
    logging: 
      driver: gelf 
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/docker:/etc/nginx/certs:rw
    networks:
      - proxy_nw
    volumes_from:
      - proxy
    logging: 
      driver: gelf 
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "letsencrypt"

networks:
  proxy_nw:
    external: true
