version: '2.3'
services:
  proxy:
    image: nginx
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_nw
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf

networks:
  proxy_nw:
    external: true
