# Scan this file for changes every 30 seconds
# https://docs.rs/log4rs/0.8.3/log4rs/encode/pattern/index.html
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%s.%f)} {l} [{h({t})}] {I}: {m}{n}"

  stdout_ref:
    kind: console
    encoder:
      pattern: "{f}:{L} {l} [{h({t})}] {I}: {m}{n}"

  tvm_stdout:
    kind: console
    encoder:
      pattern: "{m}{n}"

root:
  level: warn
  appenders:
    - stdout

loggers:
  # node messages
  node:
    level: debug
    appenders:
      - stdout

  ton_node:
    level: trace
    additive: false
    appenders:
      - stdout

  # adnl messages
  adnl:
    level: debug
    appenders:
      - stdout

  # block messages
  ton_block:
    level: debug
    appenders:
      - stdout

  # block messages
  executor:
    level: debug
    appenders:
      - stdout

  # tvm messages
  tvm:
    level: trace
    appenders:
      - tvm_stdout

  librdkafka:
    level: warn
    appenders:
      - stdout

  validator:
    level: debug
    appenders:
      - stdout_ref        
