
- name: "Create /opt dir"
  shell: 'mkdir -p /opt'
  tags: 
    - install
    - reinstall

- name: "Copy build files"
  copy:
    src: '.'
    dest: '/opt/{{ role_name }}/'
    mode: 0755
  tags:
    - install
    - reinstall

- name: "Template docker-compose.yml"
  template:
    src: 'docker-compose.yml'
    dest: '/opt/{{ role_name }}'
    mode: 0755
  tags: 
    - install
    - reinstall

- name: "Shut down docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose down'
  tags: 
   - stop
   - reinstall
 
- name: "Cleanup volumes"
  shell: 'docker volume prune -f'
  tags:
   - reinstall

- name: "Run docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose up -d'
  tags: 
    - install
    - reinstall

- name: "Check if kafka is available"
  shell: 'docker ps | grep check-connect | grep  healthy'
  retries: 50
  delay: 5
  register: result
  until: result.rc == 0
  tags: 
    - install
    - reinstall
