version: '2'
services:
  web.root:
    image: nginx:1.13.12
    container_name: web-root
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: '{{ WEBROOT_VIRTUAL_HOST | default(inventory_hostname) }}'
      LETSENCRYPT_HOST: '{{ LETSENCRYPT_HOST | default(inventory_hostname) }}'
      LETSENCRYPT_EMAIL: '{{ LETSENCRYPT_EMAIL }}'
    networks:
      - proxy_nw
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    expose:
      - "80"
    logging: 
      driver: gelf 
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "web.root"

networks:
  proxy_nw:
    external: true
