---
- name: Remove Scripts dir
  file:
    state: absent
    path: "{{ item }}/"
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - upgrade

- name: create rust user group
  group:
    name: rust
  tags:
    - install

- name: Create Scripts dir
  file:
    state: directory
    path: "{{ item }}/"
    mode: 0775
    group: rust
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - install
   - upgrade

- name: Copy scripts to remote
  copy:
    src: "{{ item }}"
    dest: "{{ scripts_dir }}"
    mode: 0775
    group: rust
  with_fileglob:
    - ../scripts/*
  tags: 
    - install
    - upgrade

- name: Install dependencies
  shell: '{{ scripts_dir }}/install_deps.sh'
  tags: install

- name: Template env file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "env.sh.j2", "dest": "{{ scripts_dir }}/env.sh"}
  when: build == true
  tags:
   - install
   - upgrade

- name: Create rustnode user
  user:
    name: rustnode
    create_home: no
    shell: /usr/sbin/nologin
    group: rust
  tags:
   - install

- name: Start remote build
  shell: "cd {{ scripts_dir }} && . ./env.sh  && ./build.sh"
  when: build == true
  tags: 
   - install
   - upgrade

- name: Install node tools from repo
  shell: '{{ scripts_dir }}/get_release.sh {{ release_version }} {{ git_repo }}'
  when: build == false
  tags: 
   - install
   - upgrade

- name: Keygen for console
  command: keygen
  tags:
   - install
   - reinstall
  register: console

- set_fact:
    console_pub: "{{ console.stdout | from_json | json_query('public') | to_json }}"
  tags:
   - install
   - reinstall

- set_fact:
    console_pvt: "{{ console.stdout | from_json | json_query('private') | to_json }}"
  tags:
   - install
   - reinstall
