version: '2.3'
services:
  arangodb:
    build:
      context: ./build
    # image: tonlabs/arango:latest
    container_name: arangodb
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: '{{ ARANGO_NO_AUTH }}'
      VIRTUAL_HOST: '{{ ARANGODB_VIRTUAL_HOST | default("arangodb." + inventory_hostname) }}'
      VIRTUAL_PORT: '{{ ARANGODB_VIRTUAL_PORT }}'
      LETSENCRYPT_HOST: '{{ LETSENCRYPT_HOST | default(inventory_hostname) }}'
      LETSENCRYPT_EMAIL: '{{ LETSENCRYPT_EMAIL }}'
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: '{{ ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY }}'
      ARANGO_ROOT_PASSWORD: '{{ ARANGO_ROOT_PASSWORD }}'
      NETWORK_TYPE: '{{ NETWORK_TYPE }}'
      INSTANCE_NAME: '{{ INSTANCE_NAME }}'
      ARANGO_SERVICE_SERVICE_HOST: '{{ ARANGO_SERVICE_SERVICE_HOST }}'
      ARANGO_SERVICE_SERVICE_PORT: '{{ ARANGO_SERVICE_SERVICE_PORT }}'
      ARANGONI_SERVICE_SERVICE_HOST: '{{ ARANGONI_SERVICE_SERVICE_HOST }}'
      ARANGONI_SERVICE_SERVICE_PORT: '{{ ARANGONI_SERVICE_SERVICE_PORT }}'
    networks:
      - proxy_nw
    volumes:
      - db3:/var/lib/arangodb3
      - data:/arango/db
      - ./arango-config:/arango/config
    expose:
      - "8529"
    mem_limit: 32G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "arangodb"

  arangodb-metrics:
    container_name: arangodb-metrics
    image: arangodb/arangodb-exporter:0.1.3
    ports:
      - 9101:9101
    networks:
      - proxy_nw
    command: "--arangodb.endpoint=http://arangodb:8529"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "arangodb"

  arangodbni:
    build:
      context: ./build
    # image: tonlabs/arango:latest
    container_name: arangodbni
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: '{{ ARANGONI_NO_AUTH }}'
      VIRTUAL_HOST: '{{ ARANGONI_VIRTUAL_HOST | default("arangodbni." + inventory_hostname) }}'
      VIRTUAL_PORT: '{{ ARANGONI_VIRTUAL_PORT }}'
      LETSENCRYPT_HOST: '{{ ARANGONI_LETSENCRYPT_HOST | default(inventory_hostname) }}'
      LETSENCRYPT_EMAIL: '{{ ARANGONI_LETSENCRYPT_EMAIL }}'
      ARANGO_ROOT_PASSWORD: '{{ ARANGO_ROOT_PASSWORD }}'
      NETWORK_TYPE: '{{ NETWORK_TYPE }}'
      INSTANCE_NAME: '{{ INSTANCE_NAME }}'
      ARANGO_SERVICE_SERVICE_HOST: '{{ ARANGO_SERVICE_SERVICE_HOST }}'
      ARANGO_SERVICE_SERVICE_PORT: '{{ ARANGO_SERVICE_SERVICE_PORT }}'
      ARANGONI_SERVICE_SERVICE_HOST: '{{ ARANGONI_SERVICE_SERVICE_HOST }}'
      ARANGONI_SERVICE_SERVICE_PORT: '{{ ARANGONI_SERVICE_SERVICE_PORT }}'
    networks:
      - proxy_nw
    volumes:
      - db3ni:/var/lib/arangodb3
      - datani:/arango/db
      - ./arangoni-config:/arango/config
    expose:
      - "8529"
    mem_limit: 32G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "arangodbni"

  arangodbni-metrics:
    container_name: arangodbni-metrics
    image: arangodb/arangodb-exporter:0.1.3
    ports:
      - 9111:9101
    networks:
      - proxy_nw
    command: "--arangodb.endpoint=http://arangodbni:8529"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://{{ hostvars[groups['ELK'][0]].inventory_hostname }}:12201"
        tag: "arangodb"

networks:
  proxy_nw:
    external: true
volumes:
  data:
  db3:
  datani:
  db3ni:
