---
- name: Remove Scripts dir
  file:
    state: absent
    path: "{{ item }}/"
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - upgrade

- name: create rust user group
  group:
    name: rust
  tags:
    - install

- name: Create Scripts dir
  file:
    state: directory
    path: "{{ item }}/"
    mode: 0775
    group: rust
  with_items:
   - "{{ scripts_dir }}"
  tags:
   - install
   - upgrade

- name: Copy scripts to remote
  copy:
    src: "{{ item }}"
    dest: "{{ scripts_dir }}"
    mode: 0775
    group: rust
  with_fileglob:
    - ../scripts/*
  tags: 
    - install
    - upgrade

- name: Install dependencies
  shell: '{{ scripts_dir }}/install_deps.sh'
  tags: install

- name: "Install docker"
  shell: 'which docker | grep -o docker || curl -fsSL https://get.docker.com | sh'
  tags: install

- name: "Install docker-compose"
  shell: 'which docker-compose | grep -o docker-compose || curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  tags: install

- name: "Install docker-compose | chmod"
  shell: 'chmod +x /usr/local/bin/docker-compose'
  tags: install

- name: "Create proxy network"
  shell: 'docker network create proxy_nw || true '
  tags: install
