---
- name: arangodb
  hosts: arangodb
  remote_user: root
  roles:
    - pre-install
    - arangodb

- name: q-server
  hosts: q-server
  remote_user: root
  roles:
    - q-server

- name: kafka
  hosts: kafka
  remote_user: root
  roles:
    - kafka

- name: rustnode
  hosts: rustnode
  remote_user: root
  roles:
   - statsd
   - rustnode
