mappings:
  - match: "kafka.stats.cluster.*.overall.*.*"
    name: "kafka_operation"
    match_metric_type: counter
    labels:
      cluster_name: "$1"
      transaction_type: "$2"
      transaction_result: "$3"
  - match: "kafka.stats.cluster.*.topic.*.size"
    name: "topic_message_size"
    match_metric_type: gauge
    labels:
      cluster_name: "$1"
      topic_name: "$2"
  - match: "kafka.stats.cluster.*.last_block"
    name: "last_block_number"
    match_metric_type: gauge
    labels:
      cluster_name: "$1"
  - match: "qserver.doc.count"
    name: "q_doc_count"
  - match: "qserver.query.time"
    name: "q_query_time"
  - match: "qserver.query.count"
    name: "q_query_count"
  - match: "qserver.query.active"
    name: "q_query_active"
  - match: "qserver.waitfor.active"
    name: "q_waitfor_active"
  - match: "qserver.subscription.active"
    name: "q_subscription_active"
  - match: "qserver.heap.space.*.*"
    name: "q_heap_space_${1}_${2}"
  - match: "rnode.shards_client_mc_block"
    name: "rnode_shards_client_mc_block"
    match_metric_type: gauge
  - match: "rnode.last_applied_mc_block"
    name: "rnode_last_applied_mc_block"
    match_metric_type: gauge
