---
- name: Create statsd user
  user:
    name: statsd
    create_home: no
    shell: /usr/sbin/nologin
  tags: install

- name: Create config directory
  file: 
    path: "{{ statsd_conf_dir }}"
    state: directory
    owner: statsd
    mode: '0755'
  tags: install

- name: Install statsd
  shell: "{{ scripts_dir }}/statsd.sh {{ statsd_version }}"
  tags: install
