
- name: "Create /opt dir"
  shell: 'mkdir -p /opt'
  tags: up

- name: "Copy build files"
  copy:
    src: '.'
    dest: '/opt/{{ role_name }}/'
    mode: 0755
  tags: up

- name: "Template docker-compose.yml"
  template:
    src: 'docker-compose.yml'
    dest: '/opt/{{ role_name }}'
    mode: 0755
  tags: up

- name: "Create htpasswd files"
  htpasswd:
    path: '/opt/{{ role_name }}/htpasswd/{{ item }}'
    name: '{{ username }}'
    password: '{{ password }}'
    mode: 0640
  tags: up
  with_items:
    - "{{ ARANGODB_VIRTUAL_HOST | default('arangodb.' + inventory_hostname) }}"
    - "{{ ARANGONI_VIRTUAL_HOST | default('arangodbni.' + inventory_hostname) }}"
  when: auth == True

- name: "Run docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose up -d --build'
  tags: up

- name: "Shut down docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose down'
  tags: down
